Update error
        /Users/jonathanong/Workspace/analytics/node_modules/useragent/index.js:378
          require('./lib/update')(function updating(err, results) {
                                 ^
        TypeError: object is not a function
            at updater (/Users/jonathanong/Workspace/analytics/node_modules/useragent/index.js:378:26)
            at Object.<anonymous> (/Users/jonathanong/Workspace/analytics/lib/useragent.js:3:1)
            at Module._compile (module.js:449:26)
            at Object.Module._extensions..js (module.js:467:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:312:12)
            at Module.require (module.js:362:17)
            at require (module.js:378:17)
            at Object.<anonymous> (/Users/jonathanong/Workspace/analytics/lib/index.js:6:17)
            at Module._compile (module.js:449:26)